name: "godot-ci"
on: push

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: LTC
  PROJECT_PATH: .

jobs:
  export-linux:
    name: Linux Test
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"
      - name: Setup
        run: |
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono/linux_debug.x86_64 ./linux_debug.x86_64
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono/linux_release.x86_64 ./linux_release.x86_64
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
